package org.neatcode.models;

/**
 * Records are immutable data classes that require only the type and name of fields.
 * The equals, hashCode, and toString methods, as well as the private, final fields and public constructor, are generated by the Java compiler.
 *
 * A record == a java class with:
 * - all fields as final
 * - Getters for all the fields
 * - a constructor initializing the required final attributes
 */
public record Movie(int movieId, String movieName, int movieDuration){};


/**
@RequiredArgsConstructor
@Getter
public class Movie {
    private int movieId;
    private String movieName;
    private int movieDuration;
}

 */